version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - aws cloudformation package --template-file sam.yaml --s3-bucket quest-games-packages --output-template-file sam-template.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - sam.yaml