version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install serverless -g
  build:
    commands:
      - echo Build and deploy the app
      - serverless deploy
  post_build:
    commands:
      - echo App deployed to AWS Lambda